'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cabecera_venta
    Public Property id_venta As Integer
    Public Property fecha As Nullable(Of Date)
    Public Property total As Nullable(Of Decimal)
    Public Property id_user As Nullable(Of Integer)
    Public Property id_cliente As Nullable(Of Integer)

    Public Overridable Property clientes As clientes
    Public Overridable Property detalle_venta As ICollection(Of detalle_venta) = New HashSet(Of detalle_venta)
    Public Overridable Property usuarios As usuarios

End Class
