'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalle_venta
    Public Property id_detalle As Integer
    Public Property id_venta As Integer
    Public Property id_producto As Nullable(Of Integer)
    Public Property cantidad As Integer

    Public Overridable Property cabecera_venta As cabecera_venta
    Public Overridable Property productos As productos

End Class
