'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class productos
    Public Property id_producto As Integer
    Public Property nombre As String
    Public Property id_categoria As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)
    Public Property precio As Nullable(Of Decimal)
    Public Property stock As Nullable(Of Integer)
    Public Property stockminimo As Nullable(Of Integer)
    Public Property id_prov As Nullable(Of Integer)

    Public Overridable Property categoria As categoria
    Public Overridable Property detalle_venta As ICollection(Of detalle_venta) = New HashSet(Of detalle_venta)
    Public Overridable Property proveedores As proveedores

End Class
