'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SisVentasEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SisVentasEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property tblCabecera() As DbSet(Of tblCabecera)
    Public Overridable Property tblCategoria() As DbSet(Of tblCategoria)
    Public Overridable Property tblCliente() As DbSet(Of tblCliente)
    Public Overridable Property tblDetalle() As DbSet(Of tblDetalle)
    Public Overridable Property tblProducto() As DbSet(Of tblProducto)
    Public Overridable Property tblProveedores() As DbSet(Of tblProveedores)
    Public Overridable Property tblUsuarios() As DbSet(Of tblUsuarios)

End Class
