'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCabecera
    Public Property id_venta As Integer
    Public Property fecha As Nullable(Of Date)
    Public Property total As Nullable(Of Decimal)
    Public Property id_user As Nullable(Of Integer)
    Public Property id_cliente As Nullable(Of Integer)
    Public Property estado As String

    Public Overridable Property tblCliente As tblCliente
    Public Overridable Property tblUsuarios As tblUsuarios
    Public Overridable Property tblDetalle As ICollection(Of tblDetalle) = New HashSet(Of tblDetalle)

End Class
