'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProducto
    Public Property id_producto As Integer
    Public Property nombre As String
    Public Property id_categoria As Nullable(Of Integer)
    Public Property estado As String
    Public Property precio As Nullable(Of Decimal)
    Public Property stock As Nullable(Of Integer)
    Public Property stockminimo As Nullable(Of Integer)
    Public Property id_proveedor As Nullable(Of Integer)

    Public Overridable Property tblCategoria As tblCategoria
    Public Overridable Property tblDetalle As ICollection(Of tblDetalle) = New HashSet(Of tblDetalle)
    Public Overridable Property tblProveedores As tblProveedores

End Class
