'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblUsuarios
    Public Property id_user As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property dni As String
    Public Property tipo As String
    Public Property estado As String
    Public Property correo As String
    Public Property direccion As String
    Public Property pass As String
    Public Property imagen As Byte()

    Public Overridable Property tblCabecera As ICollection(Of tblCabecera) = New HashSet(Of tblCabecera)

End Class
