'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuarios
    Public Property id_user As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property dni As Nullable(Of Integer)
    Public Property tipo As Nullable(Of Integer)
    Public Property estado As Nullable(Of Integer)
    Public Property correo As String
    Public Property direccion As String
    Public Property pass As String
    Public Property imagen As Byte()

    Public Overridable Property cabecera_venta As ICollection(Of cabecera_venta) = New HashSet(Of cabecera_venta)

End Class
